version: '3'
networks:
  backend:
    driver: bridge

services:
  invoice-server:
    build:
      context: ./ecpay-invoice-service
    restart: always 
    volumes:
      - ./volumes/ecpay-invoice-service/logs:/app/logs
    ports:
      - "3123:3123" 
 